artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/GuruChandra/DataSet/raw/refs/heads/main/brain_tumor_mri_dataset.zip
  local_data_file: artifacts/data_ingestion/brain_tumor_mri_dataset.zip
  unzip_dir: artifacts/data_ingestion